#!/usr/bin/env python
# authors:
# Tony Vattathil tonynv@amazon.com
"""
 Python Class License: Apache 2.0
"""

import os
import platform
import subprocess

osinfo = platform.uname()
print "\x1b[0;30;46m [INITALIZING taskcat Installer!!]\x1b[0m" 

darwin_install='''
INSTALL_DIR='/usr/local/bin'
curl -s https://raw.githubusercontent.com/aws-quickstart/taskcat/master/taskcat_test.py -o taskcat
chmod 755 taskcat
if [[ $(id -u) -eq 0  ]] ; 
then 
	pip -q --no-cache-dir install taskcat --user
	cp taskcat ${INSTALL_DIR}
	echo '\n\t[taskcat] INSTALL COMPLETE' 
	echo '\t[i] taskcat is install in => ' ${INSTALL_DIR}
	echo
	echo '\n\t[taskcat] Tip: To uninstall run: ' 
	echo "\t[1] rm ${INSTALL_DIR}/taskcat"
	echo "\t[2] sudo pip uninstall taskcat"
	echo "\t[i] Answer 'y' to prompt"
else 
	pip -q --no-cache-dir install taskcat  --user
	echo '\n\t[taskcat] INSTALL COMPLETE' 
	echo '\t[i] Root previlages were not provied!' 
	echo '\t[i] taskcat is installed in => ' $(pwd)
	echo '\t[i] Please add taskcat to your path'
	echo "\t[i] sudo cp taskcat ${INSTALL_DIR}"
	echo
	echo '\n\t[taskcat] Tip: To uninstall run' 
	echo "\t[1] rm taskcat"
	echo "\t[2] pip uninstall taskcat"
	echo "\t[i] Answer 'y' to prompt"
fi 
'''




if osinfo[0] == 'Darwin':
	install_exit_code = subprocess.call(darwin_install, shell=True)
	#run_exit_code = subprocess.call('./taskcat', shell=True)
