#!/usr/bin/env python
# authors:
# Tony Vattathil tonynv@amazon.com
"""
 Python Class License: Apache 2.0
"""

from __future__ import print_function
from __future__ import absolute_import

import sys
if sys.version_info[0] < 3:
    raise Exception("This version of the taskcat \
installer is supported only on Python 3\n\
Install python3 and retry install\n\
Or use: unsupported python 2 installer (pip2-install)\
	")
    sys.exit(1)

import os
import platform
import subprocess

osinfo = platform.uname()
print ("[INITALIZING taskcat Installer!!]") 

darwin_install='''
INSTALL_DIR='/usr/local/bin'
curl -s https://raw.githubusercontent.com/aws-quickstart/taskcat/master/taskcat_test.py -o taskcat
if [[ $(id -u) -eq 0  ]] ; 
then 
	pip3 -q --no-cache-dir install taskcat --user
	mv taskcat ${INSTALL_DIR}
	chmod 755 ${INSTALL_DIR}/taskcat
	echo '\n\t[taskcat] INSTALL COMPLETE' 
	echo '\t[i] taskcat is install in => ' ${INSTALL_DIR}
	echo
	echo '\n\t[taskcat] Tip: To uninstall run: ' 
	echo "\t[1] rm ${INSTALL_DIR}/taskcat"
	echo "\t[2] sudo pip3 uninstall taskcat"
	echo "\t[i] Answer 'y' to prompt"
else 
	pip3 -q --no-cache-dir install taskcat  --user
	chmod 755 taskcat
	echo '\n\t[taskcat] INSTALL COMPLETE' 
	echo '\t[i] Root previlages were not provied!' 
	echo '\t[i] taskcat is installed in => ' $(pwd)
	echo '\t[i] Please add taskcat to your path'
	echo "\t[i] sudo mv taskcat ${INSTALL_DIR}"
	echo
	echo '\n\t[taskcat] Tip: To uninstall run' 
	echo "\t[1] rm taskcat"
	echo "\t[2] pip3 uninstall taskcat"
	echo "\t[i] Answer 'y' to prompt"
fi 
'''




if osinfo[0] == 'Darwin':
	install_exit_code = subprocess.call(darwin_install, shell=True)
	install_exit_code = subprocess.call('taskcat', shell=True)
