import re

password_size_re = re.compile('(?!\w+_)\d{1,2}', re.IGNORECASE)
password_type_re = re.compile('(?<=_genpass_)((\d+)(\w)(\]))', re.IGNORECASE)
generate_password_requested_re = re.compile('\$\[\w+_genpass?(\w)_\d{1,2}\w?]$', re.IGNORECASE)
generate_random_string_requested_re = re.compile('\$\[taskcat_random-string]$', re.IGNORECASE)
generate_random_number_requested_re = re.compile('\$\[taskcat_random-numbers]$', re.IGNORECASE)
autobucket_requested_re = re.compile('\$\[taskcat_autobucket]$', re.IGNORECASE)
generate_az_requested_re = re.compile('\$\[\w+_ge[nt]az_\d]', re.IGNORECASE)
generate_single_az_requested_re = re.compile('\$\[\w+_ge[nt]singleaz_\d]', re.IGNORECASE)
generate_uuid_requested_re = re.compile('\$\[\w+_gen[gu]uid]', re.IGNORECASE)
default_keypair_requested_re = re.compile('\$\[\w+_getkeypair]', re.IGNORECASE)
default_license_bucket_requested_re = re.compile('\$\[\w+_getlicensebucket]', re.IGNORECASE)
default_media_bucket_requested_re = re.compile('\$\[\w+_getmediabucket]', re.IGNORECASE)
license_content_requested_re = re.compile('\$\[\w+_getlicensecontent].*$', re.IGNORECASE)
presigned_url_requested_re = re.compile('\$\[\w+_presignedurl],(.*?,){1,2}.*?$', re.IGNORECASE)
s3_replacement_requested_re = re.compile('\$\[\w+_url_.+]$', re.IGNORECASE)
get_url_re = re.compile('(?<=._url_)(.+)(?=]$)', re.IGNORECASE)
get_val_requested_re = re.compile('(?<=._getval_)(\w+)(?=]$)', re.IGNORECASE)
