#!/usr/bin/env python
# authors:
# Tony Vattathil tonynv@amazon.com
"""
 Python Class License: Apache 2.0
"""

from __future__ import absolute_import
from __future__ import print_function

import sys
import platform
import subprocess

if sys.version_info[0] < 3:
    # noinspection PyPep8,PyPep8
    raise Exception("This version of the taskcat \
installer is supported only on Python 3\n\
Install python3 and retry install\n\
Or use: unsupported python 2 installer (pip2-install)\
	")

osinfo = platform.uname()
print("[INITALIZING taskcat Installer!!]")

# noinspection PyPep8
linux_install = '''
INSTALL_DIR='/usr/local/bin'
curl -s https://raw.githubusercontent.com/aws-quickstart/taskcat/develop/taskcat.py -o taskcat.run
chmod 755 taskcat.run
pip3 -q --no-cache-dir install taskcat
sudo mv taskcat.run ${INSTALL_DIR}/taskcat
if [ -f taskcat.run ];then
	mv taskcat.run taskcat
	echo "taskcat is installed in $(pwd)"
	echo "!taskcat needs to be added to your path!!!! "
	echo "!please manally finish installing by coping ./taskcat to your path"
	exit 1
fi

	echo '\n\t[taskcat] INSTALL COMPLETE' 
	echo '\t[i] taskcat is install in => ' ${INSTALL_DIR}
	echo
	echo '\n\t[taskcat] Tip: To uninstall run: ' 
	echo "\t[1] sudo rm ${INSTALL_DIR}/taskcat"
	echo "\t[2] sudo pip3 uninstall taskcat"
	echo "\t[i] Answer 'y' to prompt"
'''
# noinspection PyPep8
if osinfo[0] == 'Darwin':
    install_exit_code = subprocess.call(linux_install, shell=True)
    install_exit_code = subprocess.call('taskcat', shell=True)
elif osinfo[0] == 'Linux':
    install_exit_code = subprocess.call(linux_install, shell=True)
    install_exit_code = subprocess.call('taskcat', shell=True)
