#!/usr/bin/env python
# authors:
# Tony Vattathil tonynv@amazon.com
"""
 License: Apache 2.0
"""

from __future__ import absolute_import
from __future__ import print_function

import platform
import subprocess

osinfo = platform.uname()
print("[INITALIZING taskcat Installer!!]")

# noinspection PyPep8,PyPep8
linux_install = '''
INSTALL_DIR='/usr/local/bin'

if [[ -d $HOME/.aws ]]; then 
 	echo "[INFO] : Found boto profile)"
 	echo "[INFO] : Boto profile will map to container during execution"
	echo "echo \"[development image]\"" >taskcat-develop.docker
	echo "docker run -it --rm -v ${HOME}/.aws:/root/.aws -v \$(pwd):/mnt taskcat/taskcat-develop taskcat \$@" >>taskcat-develop.docker
	echo "docker run -it --rm -v ${HOME}/.aws:/root/.aws -v \$(pwd):/mnt taskcat/taskcat-develop alchemist \$@" >>alchemist-develop.docker
else  
	echo "echo [development image]" >taskcat-develop.docker
	echo "docker run -it --rm -v \$(pwd):/mnt  taskcat/taskcat-develop taskcat \$@" >> taskcat-develop.docker
	echo "docker run -it --rm -v \$(pwd):/mnt  taskcat/taskcat-develop alchemist \$@" >> alchemist-develop.docker

fi

if [[ $(id -u) -eq 0  ]] ;
then 
        docker pull taskcat/taskcat-develop:latest
        sudo mv taskcat-develop.docker ${INSTALL_DIR}/taskcat-develop
        sudo mv alchemist-develop.docker ${INSTALL_DIR}/alchemist-develop
	chmod 755 ${INSTALL_DIR}/taskcat-develop
	chmod 755 ${INSTALL_DIR}/alchemist-develop
        echo '\n\t[taskcat] INSTALL COMPLETE'
        echo '\t[i] taskcat is install in => ' ${INSTALL_DIR}
        echo '\t[i] To run dev preview of taskcat, type taskcat-develop'
        echo '\t[i] To run dev preview of alchemist, type alchemist-develop'
else 
        docker pull taskcat/taskcat-develop:latest
        mv taskcat-develop.docker taskcat-develop
        mv alchemist-develop.docker alchemist-develop
	chmod 755 ${INSTALL_DIR}/taskcat-develop
	chmod 755 ${INSTALL_DIR}/alchemist-develop
        echo '\n\t[taskcat] INSTALL COMPLETE'
        echo '\t[i] Root previlages were not provied!'
        echo '\t[i] taskcat is installed in => ' $(pwd)
        echo '\t[i] To run dev preview of taskcat, type ./taskcat-develop'
        echo '\t[i] To run dev preview of alchemist, type ./alchemist-develop'
fi
'''

# Mac
if osinfo[0] == 'Darwin':
    install_exit_code = subprocess.call(linux_install, shell=True)
elif osinfo[0] == 'Linux':
    install_exit_code = subprocess.call(linux_install, shell=True)


print("\n Ready!! type \'taskcat-develop\' to start \n")
