#!/usr/bin/env python
# authors:
# Tony Vattathil tonynv@amazon.com
"""
 License: Apache 2.0
"""

from __future__ import absolute_import
from __future__ import print_function

import platform
import subprocess

osinfo = platform.uname()
print("[INITALIZING taskcat Installer!!]")

# noinspection PyPep8,PyPep8
linux_install = '''
INSTALL_DIR='/usr/local/bin'

if [ -d $HOME/.aws ]; then 
 	echo "[INFO] : Found boto profile)"
 	echo "[INFO] : Boto profile will map to container during execution"
	echo "echo \"[dockerize]\"" >taskcat.docker
	echo "docker run -it --rm -v ${HOME}/.aws:/root/.aws -v \$(pwd):/mnt taskcat/taskcat taskcat \$@" >>taskcat.docker
	echo "docker run -it --rm -v ${HOME}/.aws:/root/.aws -v \$(pwd):/mnt taskcat/taskcat alchemist \$@" >>alchemist.docker
else  
	echo "echo [dockerize]" >taskcat.docker
	echo "echo [dockerize]" >alchemist.docker
	echo "docker run -it --rm -v \$(pwd):/mnt  taskcat/taskcat taskcat \$@" >> taskcat.docker
	echo "docker run -it --rm -v \$(pwd):/mnt  taskcat/taskcat alchemist \$@" >> alchemist.docker

fi

if [ $(id -u) -eq 0  ] ;
then 
        docker pull taskcat/taskcat
        sudo mv taskcat.docker ${INSTALL_DIR}/taskcat
        sudo mv alchemist.docker ${INSTALL_DIR}/alchemist
	chmod 755 ${INSTALL_DIR}/taskcat
	chmod 755 ${INSTALL_DIR}/alchemist
        echo '\n'
	echo '\t[i] INSTALL COMPLETE'
        echo '\t[i] tools are installed in => ' ${INSTALL_DIR}
        echo '\t[i] To run taskcat the program type taskcat'
        echo '\t[i] To run alchemist the program type alchemist'
else 
        docker pull taskcat/taskcat
        mv taskcat.docker taskcat
        mv alchemist.docker alchemist
	chmod 755 taskcat
	chmod 755 alchemist
        echo '\n'
	echo '\t[i] INSTALL COMPLETE'
        echo '\t[i] Root previlages were not provied!'
        echo '\t[i] Tools are installed in => ' $(pwd)
        echo '\t[i] Please add these tools to your path'
        echo "\t[i] Manually copy tools ${INSTALL_DIR}"
        echo '\t[i] To run taskcat the program type taskcat'
        echo '\t[i] To run alchemist the program type alchemist'
fi
'''

if osinfo[0] == 'Darwin':
    install_exit_code = subprocess.call(linux_install, shell=True)
elif osinfo[0] == 'Linux':
    install_exit_code = subprocess.call(linux_install, shell=True)

print("\n Ready!! type \'taskcat\' to start \n")
